24 doc create documentation
control-toolbox/OptimalControlProblems.jl pull request #36
Opened 2024-09-09 14:54 UTC by 0Yassine0

2024-09-09 18:48 UTC, ocots requested changes

2024-09-09 18:48 UTC, ocots commented on docs/src/use_models.md
> +To use `OptimalControl` models from `OptimalControlProblems.jl`, you need to have `CTDirect` installed.
@0Yassine0 Est-ce que tu pourras ajouter une remarque ou un bout de code en expliquant que l'on peut faire `using OptimalControl` à la place de `using CTDirect` car le premier tire le second ?

2024-09-10 09:42 UTC, 0Yassine0 commented
The failing checks should be solved after this PR #42

2024-09-10 10:05 UTC, ocots requested changes

2024-09-10 10:05 UTC, ocots commented on docs/Project.toml
> +CTDirect = "0.12.0"
For the compat, `X.Y` is sufficient.

2024-09-10 11:37 UTC, ocots approved these changes

2024-09-10 11:39 UTC, merged

2024-09-10 17:56 UTC, ocots commented
@0Yassine0 Pense à supprimer la branche après la PR. Est-ce qu'on peut supprimer celle-ci ?

2024-09-10 18:51 UTC, 0Yassine0 commented
I thought it's done automatically, sorry.