54 dev change the return value to nlp + docp
control-toolbox/OptimalControlProblems.jl pull request #55
Opened 2024-09-12 11:46 UTC by 0Yassine0

2024-09-12 12:48 UTC, ocots requested changes

2024-09-12 12:48 UTC, ocots commented on docs/src/add_problem.md
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
Maybe write 

```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return nlp, docp
```

2024-09-12 12:48 UTC, ocots commented on docs/src/solve_problem.md
> +model = chain(OptimalControlBackend())[2]
It is better to write

```julia
_, model = chain(OptimalControlBackend())
```

ou si on retourne le `nlp` en premier : 

```julia
model, _ = chain(OptimalControlBackend())
```

2024-09-12 12:48 UTC, ocots commented on docs/src/use_models.md
> +nlp = cart_pendulum(OptimalControlBackend())[2]
De même ici.

2024-09-12 12:48 UTC, ocots commented on docs/src/use_models.md
> +docp = cart_pendulum(OptimalControlBackend())[1]
```julia
docp, _ = cart_pendulum(OptimalControlBackend())
```

ou 

```julia
_, docp = cart_pendulum(OptimalControlBackend())
```

2024-09-12 12:48 UTC, ocots commented on test/test_OptimalControl_optimality.jl
> +            model = OptimalControlProblems.eval(f)(OptimalControlBackend())[2]
idem.

2024-09-12 13:23 UTC, frapac approved these changes
LGTM

2024-09-12 20:25 UTC, ocots requested changes

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/beam.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/bioreactor.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/cart_pendulum.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/chain.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/dielectrophoretic_particle.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/double_oscillator.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/ducted_fan.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/electrical_vehicle.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/glider.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/insurance.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/jackson.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/moonlander.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/quadrotor.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/robbins.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/robot.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/rocket.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/space_Shuttle.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/steering.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/truck_trailer.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-12 20:25 UTC, ocots commented on ext/OptimalControlModels/vanderpol.jl
> +    res = direct_transcription(ocp; init=init, grid_size=nh)
```julia
docp, nlp = direct_transcription(ocp; init=init, grid_size=nh)
return docp, nlp
```

2024-09-13 07:52 UTC, ocots approved these changes

2024-09-13 08:08 UTC, merged